### ISSUE TITLE
invalid bower for #0.7.2

### ISSUE THREAD

**Issue by aprooks** [vperron/leaflet-dist#10]
Hello,

you have an invalid bower for #0.7.2 tag. 
Please, push a tag 0.7.2  for updated version.

**Comment by csrx** [comment]
Looks like he made a change 6 hours ago, but we're still having issues related to bower.json
"bower leaflet-dist#0.7.x EMALFORMED Failed to read PATH/bower.json"

**Comment by aprooks** [comment]
That's because bower treats only git tagged commits as a source. So the version with a fix ( #9  )should be tagged and pushed to the repo.

**Comment by MichielDeMey** [comment]
Yea, you need to update the tag for this to be deployed to Bower.

This breaks our build system, because https://github.com/tombatossals/angular-leaflet-directive uses this repo as a dependency.

**Comment by vperron** [comment]
i'm really sorry guys, this all happened on the day I was coming back to Tokyo and was kind of jetlagged. 
Hope it's fixed now, I'll close the issue as soon as one of you confirms.

**Comment by MichielDeMey** [comment]
Did `bower cache clean` and `bower update`, which worked for me.

**Comment by csrx** [comment]
Same here. Thanks.

**Comment by vperron** [comment]
OK I guess I can close it then. Sorry for the inconvenience.
